Handle also merged commit and not only squashed commits (#169)

diff --git a/.github/actions/kosli-attest-jira/action.yml b/.github/actions/kosli-attest-jira/action.yml
--- a/.github/actions/kosli-attest-jira/action.yml
+++ b/.github/actions/kosli-attest-jira/action.yml
@@ -69,22 +69,41 @@ runs:
         if [ "${{ inputs.allow-only-branch-match }}" == "true" ]; then
           # If this is on a branch we automatically search the branch name for reference,
           # but on main branch it is more trickey.
-          # To get the original branch we need to first find the PR number from the
-          # git commit message, then get pr info from github and extract the head.ref
+
           if [ "${{ github.ref }}" == "refs/heads/main" ]; then
+            # The message format in the git log depends on the merging strategy:
+            #   Squashed PRs: Title (#123)
+            #   Merged PRs: Merge pull request #123 from kosli-dev/OPS-69-other-branch
+            # For merged PRs the message can also vary if it is the same repo or a fork, and a branch name can
+            # contain one or more slashes /
+            # So the strategy is to get the PR number in two different ways and then
+            # get PR info from github and extract the head.ref
+
             export GH_TOKEN=${{ github.token }}
-            PR_NUMBER=$(git log -1 --pretty=%B | grep "(#" | sed "s/^.*(#//;s/).*//")
-            ORIG_BRANCH=$(gh api repos/${{ github.repository }}/pulls/${PR_NUMBER} --jq .head.ref)\
-            JIRA_SECONDARY_SOURCE_ARG="--jira-secondary-source ${ORIG_BRANCH}"
+            PR_NUMBER=$(git log -1 --pretty=%B | grep "Merge pull request #" | sed "s/Merge pull request #//;s/ .*//")
+            if [ -z "$PR_NUMBER" ]; then
+              PR_NUMBER=$(git log -1 --pretty=%B | grep "(#" | sed "s/^.*(#//;s/).*//")
+            fi
+            if [ -z "$PR_NUMBER" ]; then
+              echo "ERROR: Running on main branch but failed to get a Pull request number from the git commit message" >&2
+              echo "Will continue execution since Jira issue reference might be in the commit message" >&2
+              echo "Commit message:" >&2
+              git log -1 --pretty=%B >&2
+              echo "---end commit message---" >&2
+            else
+              echo "Found PR number: ${PR_NUMBER} >&2
+              ORIG_BRANCH=$(gh api repos/${{ github.repository }}/pulls/${PR_NUMBER} --jq .head.ref)
+              JIRA_SECONDARY_SOURCE_ARG="--jira-secondary-source ${ORIG_BRANCH}"
+              echo "Found original branc: ${ORIG_BRANCH} >&2
+            fi
           fi
         else
           IGNORE_BRANCH_MATCH_ARG="--ignore-branch-match"
         fi
-        
 
         if [ "${{ inputs.report-to-kosli }}" == "false" ]; then
           # Currently the kosli attest jira command is missing a feature to not report the jira ticket,
-          # so use a grep for now
+          # so we run the command in dry-run mode and then look at the result.
           kosli attest jira \
             --name work-reference \
             --jira-base-url ${{ inputs.jira-base-url }} \
@@ -94,7 +113,24 @@ runs:
             ${IGNORE_BRANCH_MATCH_ARG} \
             ${JIRA_SECONDARY_SOURCE_ARG} \
             ${JIRA_ISSUE_ARG} \
-            --assert --dry-run 2>&1 | grep "no Jira references are found" && exit 1 || exit 0
+            --assert --dry-run &> /tmp/kosli-attest-result.txt
+      
+          # If we find a Jira issue reference the output will be like this:
+          #   "jira_results": [
+          #       {
+          #           "issue_id": "OPS-68",
+          #           "issue_url": "https://kosli-team.atlassian.net/browse/OPS-68",
+          #           "issue_exists": true
+          #       }
+          #   ]
+          if grep -q '"issue_id":' /tmp/kosli-attest-result.txt; then
+            echo "Found jira issues:"
+            grep '"issue_id":' /tmp/kosli-attest-result.txt
+          else
+            echo "ERROR: No Jira issues found" >&2
+            cat /tmp/kosli-attest-result.txt >&2
+            exit 9
+          fi
         else
           kosli attest jira \
             --name work-reference \
