Adding JIRA tickets to release

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -8,6 +8,10 @@ env:
   KOSLI_ORG: kosli-public
   KOSLI_API_TOKEN: "${{ secrets.KOSLI_PUBLIC_API_TOKEN }}"
   KOSLI_CLI_VERSION: "2.11.8"
+  KOSLI_ENV_STAGING: "jira-integration-example-staging"
+  KOSLI_ENV_PROD: "jira-integration-example-prod"
+  KOSLI_FLOW_FRONTEND: "jira-example-frontend"
+  KOSLI_FLOW_BACKEND: "jira-example-backend"
   # KOSLI_DRY_RUN: true
   JIRA_BASE_URL: "https://kosli-team.atlassian.net"
   JIRA_USERNAME: ${{ secrets.KOSLI_JIRA_USERNAME }}
@@ -26,15 +30,26 @@ jobs:
 
       - name:
         run: |
-          set -x
           source scripts/lib-jira.sh
-          current_release_json=$(get_current_release_candidate ${{ env.JIRA_PROJECT_ID }})
-          echo "${current_release_json}" | jq .
-          current_release=$(echo "${current_release_json}" | jq .values)
-          echo cr=$current_release
-          if [ "${current_release}" != "[]" ]; then
-            echo "Release candidate already exist: ${current_release}"
-            exit 1
-          fi
-          TIMESTAMP=$(date -u "+%Y-%m-%d-%H-%M-%S")
-          create_release ${{ env.JIRA_PROJECT_ID }} ${TIMESTAMP}
+          source scripts/lib-kosli.sh
+          
+          # Check if a release already exists, if so we fail
+#          CURRENT_REL_JSON=$(get_CURRENT_REL_candidate ${{ env.JIRA_PROJECT_ID }})
+#          CURRENT_REL=$(echo "${CURRENT_REL_JSON}" | jq .values)
+#          if [ "${CURRENT_REL}" != "[]" ]; then
+#            echo "Release candidate already exist: ${CURRENT_REL}"
+#            exit 1
+#          fi
+
+           # Create the release and get the release ID
+#          TIMESTAMP=$(date -u "+%Y-%m-%d-%H-%M-%S")
+#          CREATE_RESULT_JSON=$(create_release ${{ env.JIRA_PROJECT_ID }} ${TIMESTAMP})
+#          RELEASE_ID=$(echo "${CREATE_RESULT_JSON}" | jq .id)
+          RELEASE_ID=10099
+
+          # Add jira tickets to release
+          JIRA_KEYS=$(get_issue_keys_between_staging_and_prod)
+          echo "Found issues: ${JIRA_KEYS}"
+          for JIRA_KEY in ${JIRA_KEYS}; do 
+            add_issue_to_release ${JIRA_KEY} ${RELEASE_ID}
+          done
